#include <iostream>
#include <string>

using namespace std;

struct tubos_acero {
        string tipo;
        string codigo;
        int stock;
        float value;
};

int main() {
      tubos_acero[3];
      tubos_aceros[0].medida = "redondo";
      tubos_aceros[0].codigo = "tubo_acero_redondo";
      tubos_acero[0].stock = 5;
      tubos_acero[0].value = 24,6;

      tubos_aceros[0].medida = "cuadrado";
      tubos_aceros[0].codigo = "tubo_acero_cuadrado";
      tubos_acero[0].stock = 3;
      tubos_acero[0].value = 54.5;

      tubos_aceros[0].medida = "rectangular";
      tubos_aceros[0].codigo = "tubo_acero_rectangular";
      tubos_acero[0].stock = 9;
      tubos_acero[0].value = 53.4;

      cout <<"Bienvenidos a Acero Argentino \n";
      cout<<"La disponibilidad del dia es:";

      for(int i=0;i<3;i++){
          cout<<i+1<<" ."<<tubos_acceros[i].codigo<<" ."tubos_aceros[i].stock<<"en stock"tubos_aceros[i].value<<"valor del tipo de tubo"<<endl;
      }
      int tubos_acceroindex,quantify;


}
